results: Add sdm660 results extracted from Xiaomi Mi A2
kdrag0n/freqbench pull request #44
Opened 2021-11-26 19:20 UTC by Tashar02

These are the benchmark results extracted from Xiaomi Mi A2 that has a Snapdragon 660 (SDM660) running on linux-4.19.217 using freqbench.

2021-11-28 12:16 UTC, kdrag0n requested changes
Thanks! Just a few minor changes to make because this is an additional/secondary device that's different from the first one contributed for this SoC.

2021-11-28 12:16 UTC, kdrag0n commented on results/README.md
> +| sdm660     | SDM660    | Snapdragon 660  | Xiaomi Mi A2            | Unknown  |
Additional devices with the same SoC aren't currently tracked separately in the index, so there's no need to add a duplicate here.

2021-11-28 12:16 UTC, kdrag0n commented on results/sdm660/third/cmdline.txt
> +rcupdate.rcu_normal_after_boot=1 quiet noirqdebug nodebugmon kpti=off nosoftlockup=0 mce=ignore_ce cgroup_disable=pressure androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x37 ehci-hcd.park=3
Please rename `third` to the device codename, `jasmine`, as it's not the same device as `main`.

2021-11-28 12:45 UTC, Tashar02 commented on results/README.md
> +| sdm660     | SDM660    | Snapdragon 660  | Xiaomi Mi A2            | Unknown  |
Ok :)

2021-11-28 12:45 UTC, Tashar02 commented on results/sdm660/third/cmdline.txt
> +rcupdate.rcu_normal_after_boot=1 quiet noirqdebug nodebugmon kpti=off nosoftlockup=0 mce=ignore_ce cgroup_disable=pressure androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x37 ehci-hcd.park=3
Hmm, ok👍

2021-11-28 12:46 UTC, Tashar02 commented on results/sdm660/third/cmdline.txt
> +rcupdate.rcu_normal_after_boot=1 quiet noirqdebug nodebugmon kpti=off nosoftlockup=0 mce=ignore_ce cgroup_disable=pressure androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x37 ehci-hcd.park=3
Full codename is "jasmine_sprout", should I add this or just "jasmine"?

2021-11-28 13:08 UTC, kdrag0n commented on results/sdm660/third/cmdline.txt
> +rcupdate.rcu_normal_after_boot=1 quiet noirqdebug nodebugmon kpti=off nosoftlockup=0 mce=ignore_ce cgroup_disable=pressure androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x37 ehci-hcd.park=3
Just "jasmine" is fine.

2021-11-29 09:48 UTC, Tashar02 commented
@kdrag0n you can check now :)

2021-11-29 18:18 UTC, kdrag0n approved these changes

2021-11-29 18:18 UTC, kdrag0n commented
Looks good, thanks!

2021-11-29 18:18 UTC, merged

2021-11-29 19:34 UTC, Tashar02 commented
You're welcome!